[project]
authors = ["David W.H. Swenson <dwhs@hyperblazer.net>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "khatoon-communicate"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
twilio = ">=9.5.1,<10"
click = ">=8.1.8,<9"
boto3 = ">=1.37.18,<2"
nodejs = "*"

jupyter = "*"
